# Generated by Django 5.1 on 2024-08-08 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites_app', '0001_initial'),
        ('result_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
        migrations.AddField(
            model_name='favorites_result',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_result_set', to='favorites_app.favorites'),
        ),
        migrations.AddField(
            model_name='favorites_result',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='result_app.result'),
        ),
    ]
