# Generated by Django 5.1 on 2024-08-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0002_initial'),
        ('user_app', '0003_rename_affilitation_user_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_favorites', to='user_app.user'),
        ),
    ]
