# Generated by Django 5.1 on 2024-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization_alignment',
        ),
        migrations.AddField(
            model_name='profile',
            name='alignment',
            field=models.TextField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
