# Generated by Django 5.1 on 2024-08-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_profile_organization_alignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
