# Generated by Django 5.1 on 2024-08-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_alignment_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
