# Generated by Django 5.1 on 2024-08-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_favorites_result_description_favorites_result_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='category',
        ),
    ]
