# Generated by Django 5.1 on 2024-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affilitation',
            field=models.CharField(default='Citizen', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Padawan', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
