# Generated by Django 5.1 on 2024-08-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_affilitation_user_display_name_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='affilitation',
            new_name='alignment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Padawan', max_length=25),
        ),
    ]
